### ISSUE TITLE
Doesn't work when watching from Browser

### ISSUE THREAD

**Issue by MohandL3G** [oonqt/EmbyCord#1]
**Describe the bug**
When I watch something directly from the Localhost Server, Embycord doesn't recognize what I watch and doesn't show anything on Discord.

**Expected behavior**
I just expected it to work, as I though that Embycord see what I watch from Emby Server.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/31743237/70215780-e6781380-1746-11ea-8841-b1aa5e7f3480.jpg)

**Error**
[logs.zip](https://github.com/oonqt/EmbyCord/files/3925686/logs.zip)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1903

**Additional context**
I don't know, Maybe this problem is with Emby itself, Thanks anyway.

**Comment by oonqt** [comment]
Does it show as your status when playing from other clients? From your error logs, it looks like your connection to the Emby Server has been timing out

**Comment by MohandL3G** [comment]
Hi, Sorrry for late reply.
Yes it does, I always use Emby for Kodi, and it works fine, and I tried with Emby Client (on both PC and Android) and it works fine, only when running video directly from the Server.

**Comment by oonqt** [comment]
When you say directly from the server, do you mean accessing it via Localhost, Local IP, external IP, or any of those?

**Comment by MohandL3G** [comment]
Localhost

**Comment by oonqt** [comment]
I'll take a look when I have some time, I'm pretty busy right now so it might be a week or two

**Comment by oonqt** [comment]
Just tested it and it works fine when accessing it from localhost. Are you sure that the signed in user on the web dashboard is the same user that you set when you configured EmbyCord?

**Comment by MohandL3G** [comment]
Yes, I'm sure, anyway I don't know if this is a problem from EmbyCord or Emby itself, as I have so many issues from Emby, I couldn't handle it anymore, so I've changed to Jellyfin, Thank you for everything.

**Comment by oonqt** [comment]
I'm planning on trying jellyfin out again in the future and if I like it I'll just make a fork of this project and change all assets and color themes to match that of jellyfin. Last I checked Embycord still worked with Jellyfin it's just that the assets didn't match up

**Comment by MohandL3G** [comment]
I also wanted to test out Embycord with Jellyfin, and it worked, I hope to see that fork soon, Thank you so much, I'll close this Issue 😁

**Comment by oonqt** [comment]
Hello again! I just finished a small rewrite that gives you the ability to switch to the Jellyfin theme/presence. I haven't tested it too much, if you'd like to check it out you can get it (version 1.0.7) from the releases page
